name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Permissions needed for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc-aarch64-linux-gnu g++-aarch64-linux-gnu qemu-user

      - name: Configure CMake
        run: |
          mkdir build && cd build
          cmake .. \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
            -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
            -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
            -DCMAKE_CROSSCOMPILING_EMULATOR="qemu-aarch64;-L;/usr/aarch64-linux-gnu/"

      - name: Build Project
        run: cmake --build build

      - name: Run Unit Tests (via QEMU)
        run: |
          qemu-aarch64 -L /usr/aarch64-linux-gnu/ ./build/src/week1/test_week1

          qemu-aarch64 -L /usr/aarch64-linux-gnu/ ./build/src/week2/test_week2


  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Sphinx
        run: pip install sphinx sphinx-rtd-theme
      
      - name: Build Documentation
        run: |
          cd docs
          make html
      
      # This step helps us debug by showing exactly what folders exist
      - name: List files to verify path
        run: ls -R docs/
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Try changing '_build' to 'build' here
          path: 'docs/build/html'

  deploy-docs:
    runs-on: ubuntu-latest
    # This job only starts if the two previous ones finished successfully
    needs: [build-and-test, build-docs] 
    # Only deploy on pushes to the main branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4